amqp:
  admin:
    auto-create: true
  host: localhost
  port: 5672
  username: adm_videos
  password: 123456

mysql:
  username: root
  password: 123456
  schema: catalog_adm
  url: localhost:3306

server:
  port: 8081
  undertow:
    threads:
      worker: 32
      io: 4
