amqp:
  admin:
    auto-create: ${AMQP_ADMIN_AUTO_CREATE:true}
  host: ${AMQP_RABBIT_HOST:catalog_adm_rabbitmq}
  port: ${AMQP_RABBIT_PORT:5672}
  username: ${AMQP_RABBIT_USERNAME:adm_videos}
  password: ${AMQP_RABBIT_PASSWORD:123456}

keycloak:
  host: ${KEYCLOAK_HOST:catalog_adm_keycloak:8443}
  realm: ${KEYCLOAK_REALM:fc3-codeflix}

mysql:
  username: ${DATABASE_MYSQL_USERNAME:root}
  password: ${DATABASE_MYSQL_PASSWORD:123456}
  schema: catalog_adm
  url: ${DATABASE_MYSQL_URL:catalog_adm_mysql:3306}

server:
  port: 8081
  undertow:
    threads:
      worker: 32
      io: 4
