spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration

keycloak:
  host: test
  realm: http://test:8443

mysql:
  username: root
  password: 123456
  schema: catalog_adm
  url: localhost:${mysql.port}

logging:
  level:
    ROOT: info