version: '3.7'

services:
  mysql:
    container_name: catalog_adm_mysql
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=catalog_adm
    security_opt:
      - seccomp:unconfined
    ports:
      - 3306:3306
    networks:
      - catalog_adm_network

networks:
  catalog_adm_network: