version: '3.7'

services:
  app:
    container_name: catalog_adm_app
    build:
      context: ../../
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - 8081:8081
    networks:
      - catalog_adm_network
      - catalog_adm_services

networks:
  catalog_adm_network:
  catalog_adm_services:
    external: true